# Generated by Django 5.0.6 on 2024-06-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_avion_remove_staff_aeroport_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aeroport',
        ),
    ]
