# Generated by Django 5.0.6 on 2024-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_ref', models.IntegerField()),
                ('user_ref', models.IntegerField()),
                ('demande', models.BooleanField(default=False)),
                ('annulation', models.BooleanField(default=False)),
            ],
        ),
    ]
