services:
  web: 
    build:
      context: app
      dockerfile: django-compose/app/Dockerfile
      target: builder
    ports: 
      - '8000:8000'
      - '80:80'
      - '443:443'
    networks:
      - bridge_network


networks:
  bridge_network:
    driver: bridge
