services:


##### DATABASE #####
  db:
    container_name: db
    hostname: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: makarov_airport
      MYSQL_USER: gab
      MYSQL_PASSWORD: toto
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bridge_network
####################

###### API REST ########
  web-rest-1:
    container_name: web-rest-1
    hostname: web-rest-1
    build:
      context: django-compose-user/app
      target: builder
    ports: 
      - '8000:8000'
      - '81:80'
      - '444:443'
    networks:
      - bridge_network

  web-rest-2:
    container_name: web-rest-2
    hostname: web-rest-2
    build:
      context: django-compose-vols/app
      target: builder
    ports:
      - '8001:8000'
      - '82:80'
      - '445:443'
    networks:
      - bridge_network

  web-rest-3:
    container_name: web-rest-3
    hostname: web-rest-3
    build:
      context: django-compose-reservations/app
      target: builder
    ports:
      - '8002:8000'
      - '83:80'
      - '446:443'
    networks:
      - bridge_network

  web-rest-4:
    container_name: web-rest-4
    hostname: web-rest-4
    build:
      context: django-compose-structure/app
      target: builder
    ports:
      - '8003:8000'
      - '84:80'
      - '447:443'
    networks:
      - bridge_network
############################


##### NATS CLUSTER #####
  nats:
    container_name: nats
    hostname: nats
    image: nats
    ports:
      - "8222:8222"
    networks:
      - bridge_network
########################


##### PYTHON MICROSERVICES #####
  micro1:
    container_name: micro1
    hostname: micro1
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script1.py

  micro2:
    container_name: micro2
    hostname: micro2
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script2.py

  micro3:
    container_name: micro3
    hostname: micro3
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script3.py
################################


networks:
  bridge_network:
    driver: bridge
volumes:
  db-data:
    name: "maria-data"

