services:


##### DATABASE #####
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: makarov_airport
      MYSQL_USER: gab
      MYSQL_PASSWORD: toto
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      my_network:
        ipv4_address: 172.21.0.5
####################

###### API REST ########
  web-rest-1:
    build:
      context: django-compose-user/makarov_users
      target: builder
    ports: 
      - '8000:8000'
      - '81:80'
      - '444:443'
    networks:
      my_network:
        ipv4_address: 172.21.0.1
    depends_on:
      - db

  web-rest-2:
    build:
      context: django-compose-vols/makarov_vols
      target: builder
    ports:
      - '8001:8000'
      - '82:80'
      - '445:443'
    networks:
      my_network:
        ipv4_address: 172.21.0.2
    depends_on:
      - db

  web-rest-3:
    build:
      context: django-compose-reservations/makarov_reservations
      target: builder
    ports:
      - '8001:8000'
      - '82:80'
      - '445:443'
    networks:
      my_network:
        ipv4_address: 172.21.0.3
    depends_on:
      - db

  web-rest-4:
    build:
      context: django-compose-structure/makarov_structure
      target: builder
    ports:
      - '8001:8000'
      - '82:80'
      - '445:443'
    networks:
      my_network:
        ipv4_address: 172.21.0.4
    depends_on:
      - db
####################################

##### NATS CLUSTER #####
  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      my_network:
        ipv4_address: 172.21.0.10
########################


##### PYTHON MICROSERVICES #####
  micro1:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      my_network:
        ipv4_address: 172.21.0.20
    command: python3 script1.py

  micro2:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      my_network:
        ipv4_address: 172.21.0.21
    command: python3 script2.py

  micro3:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      my_network:
        ipv4_address: 172.21.0.22
    command: python3 script3.py
################################


##### FRONT DJANGO ######
  djangopache:
    build:
      dockerfile: djangopache-compose/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      my_network:
        ipv4_address: 172.21.0.30
#########################

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  db-data:
    name: "maria-data"