services:


  web-rest:
    build:
      context: django-compose/app
      target: builder
    ports: 
      - '8000:8000'
      - '80:80'
      - '443:443'
    networks:
      - bridge_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bridge_network

  nats:
    image: nats
    ports:
      - "8222:8222"
    networks:
      - bridge_network

  micro1:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script1.py

  micro2:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script2.py

  micro3:
    build:
      dockerfile: microservices-compose/Dockerfile
      target: micropy
    networks:
      - bridge_network
    command: python3 script3.py


networks:
  bridge_network:
    driver: bridge

volumes:
  db-data:
    name: "maria-data"

