services:


##### DATABASE #####
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: makarov_airport
      MYSQL_USER: gab
      MYSQL_PASSWORD: toto
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      my_network:
        ipv4_address: 172.21.0.5
####################

###### API REST ########
  web-rest-1:
    build:
      context: django-compose-user/makarov_users
      target: builder
    ports: 
      - '8000:8000'
      - '81:80'
      - '444:443'
    networks:
      my_network:
        ipv4_address: 172.21.0.4
    depends_on:
      - db

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  db-data:
    name: "maria-data"