services:
  web: 
    build:
      context: app
      dockerfile: django-compose/app/Dockerfile
      target: builder
    ports: 
      - '8000:8000'
      - '80:80'
      - '443:443'
    networks:
      - bridge_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bridge_networks



networks:
  bridge_network:
    driver: bridge
