# Generated by Django 5.0.6 on 2024-06-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banque',
            old_name='code',
            new_name='rib',
        ),
    ]
