# Generated by Django 5.0.6 on 2024-06-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_pays', models.CharField(max_length=3)),
                ('fuseau', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Avions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('places', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.IntegerField()),
                ('level', models.CharField(max_length=2)),
                ('aeroport_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_aeroport', to='structure.aeroports')),
            ],
        ),
    ]
