# Generated by Django 5.0.6 on 2024-06-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_avions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_ref',
            field=models.CharField(max_length=100),
        ),
    ]
