# Generated by Django 5.0.6 on 2024-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0002_remove_vol_aeroport_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='numero_vol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
