# Generated by Django 5.0.6 on 2024-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0004_rename_numero_vol_vol_numvol'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='avion_ref',
            field=models.CharField(default='boeing 747', max_length=100),
            preserve_default=False,
        ),
    ]
