# Generated by Django 5.0.6 on 2024-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avions',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
